// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToBuyListV1;

#nullable disable

namespace ToBuyListV1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToBuyListV1.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MonthlyBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("YearlyBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Budgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MonthlyBudget = 2000.00m,
                            TotalSpent = 500.00m,
                            UserId = 1,
                            YearlyBudget = 24000.00m
                        },
                        new
                        {
                            Id = 2,
                            MonthlyBudget = 1500.00m,
                            TotalSpent = 300.00m,
                            UserId = 2,
                            YearlyBudget = 18000.00m
                        });
                });

            modelBuilder.Entity("ToBuyListV1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPurchased = false,
                            LastUpdated = new DateTime(2024, 11, 21, 3, 3, 58, 652, DateTimeKind.Utc).AddTicks(386),
                            Name = "Laptop",
                            Price = 1200.00m,
                            Priority = 1,
                            Url = "https://example.com/laptop",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsPurchased = false,
                            LastUpdated = new DateTime(2024, 11, 14, 3, 3, 58, 652, DateTimeKind.Utc).AddTicks(1388),
                            Name = "Smartphone",
                            Price = 800.00m,
                            Priority = 2,
                            Url = "https://example.com/smartphone",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsPurchased = true,
                            LastUpdated = new DateTime(2024, 11, 21, 3, 3, 58, 652, DateTimeKind.Utc).AddTicks(1558),
                            Name = "Headphones",
                            Price = 150.00m,
                            Priority = 3,
                            Url = "https://example.com/headphones",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ToBuyListV1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OAuthId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "John Doe",
                            Email = "user1@example.com",
                            OAuthId = "google-oauth-id-1"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Jane Smith",
                            Email = "user2@example.com",
                            OAuthId = "google-oauth-id-2"
                        });
                });

            modelBuilder.Entity("ToBuyListV1.Models.Budget", b =>
                {
                    b.HasOne("ToBuyListV1.Models.User", "User")
                        .WithOne("UserBudget")
                        .HasForeignKey("ToBuyListV1.Models.Budget", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToBuyListV1.Models.Product", b =>
                {
                    b.HasOne("ToBuyListV1.Models.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToBuyListV1.Models.User", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("UserBudget")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
